name: xprex
description: "XpreX - Vertical video sharing platform with monetization features"
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  
  # State & Routing
  flutter_riverpod: ^3.0.0
  go_router: ^17.0.0
  
  # Backend
  supabase_flutter: '>=1.10.0'
  http: ^1.0.0
  
  # Video & Media
  video_player: '>=2.9.2'
  video_thumbnail: 0.5.6
  image_picker: '>=1.1.2'
  cached_network_image: ^3.0.0
  
  # Utilities
  share_plus: ^12.0.0
  wakelock_plus: ^1.0.0
  path: ^1.0.0
  path_provider: ^2.0.0
  shared_preferences: ^2.0.0
  intl: 0.20.2
  timeago: ^3.6.1
  
  # --- THE FIX: Git Dependency ---
  # We use a fixed version of Paystack that supports Flutter 3+
  flutter_paystack:
    git:
      url: https://github.com/definitely-not-god/flutter_paystack.git
      ref: master

# We keep the overrides just in case the fork has slight version mismatches
dependency_overrides:
  intl: 0.20.2
  http: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/edgy_tech_monogram_X_logo_sharp_angles_vibrant_gradient_turquoise_1763918747193.png
  remove_alpha_ios: true
